
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: keystore.jks
      keyStorePassword: iamiam
      keyStoreType: JKS
      supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2, SSLv3]
      validateCerts: false
      validatePeers: false

logging:
  level: INFO
  loggers:
    task.lt: DEBUG
